sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "8"
  - '6.10.3'
before_install:
  - npm i -g npm
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release